ngnix

diff --git a/alpine-nginx/Dockerfile b/alpine-nginx/Dockerfile
--- a/alpine-nginx/Dockerfile
+++ b/alpine-nginx/Dockerfile
@@ -2,10 +2,15 @@ FROM docker.repo/alpine-base:3.9.4
 
 LABEL maintainer="NGINX Docker Maintainers <docker-maint@nginx.com>"
 
-ENV NGINX_VERSION 1.16.0
+ENV NGINX_VERSION 1.17.2
 
-RUN GPG_KEYS=B0F4253373F8F6F510D42178520A9993A1C052F8 \
-	&& CONFIG="\
+ENV LANG=C.UTF-8
+
+#WORKDIR /temp
+
+ADD nginx-${NGINX_VERSION}.tar.gz /usr/src/
+
+RUN CONFIG="\
 		--prefix=/etc/nginx \
 		--sbin-path=/usr/sbin/nginx \
 		--modules-path=/usr/lib/nginx/modules \
@@ -65,25 +70,28 @@ RUN GPG_KEYS=B0F4253373F8F6F510D42178520A9993A1C052F8 \
 		libxslt-dev \
 		gd-dev \
 		geoip-dev \
-	&& curl -fSL http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz -o nginx.tar.gz \
-	&& curl -fSL http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz.asc  -o nginx.tar.gz.asc \
-	&& export GNUPGHOME="$(mktemp -d)" \
-	&& found=''; \
-	for server in \
-		ha.pool.sks-keyservers.net \
-		hkp://keyserver.ubuntu.com:80 \
-		hkp://p80.pool.sks-keyservers.net:80 \
-		pgp.mit.edu \
-	; do \
-		echo "Fetching GPG key $GPG_KEYS from $server"; \
-		gpg --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$GPG_KEYS" && found=yes && break; \
-	done; \
-	test -z "$found" && echo >&2 "error: failed to fetch GPG key $GPG_KEYS" && exit 1; \
-	gpg --batch --verify nginx.tar.gz.asc nginx.tar.gz \
-	&& rm -r "$GNUPGHOME" nginx.tar.gz.asc \
-	&& mkdir -p /usr/src \
-	&& tar -zxC /usr/src -f nginx.tar.gz \
-	&& rm nginx.tar.gz \
+
+
+	# && curl -fSL http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz -o nginx.tar.gz \
+	# && curl -fSL http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz.asc  -o nginx.tar.gz.asc \
+	# && export GNUPGHOME="$(mktemp -d)" \
+	# && found=''; \
+	# for server in \
+	# 	ha.pool.sks-keyservers.net \
+	# 	hkp://keyserver.ubuntu.com:80 \
+	# 	hkp://p80.pool.sks-keyservers.net:80 \
+	# 	pgp.mit.edu \
+	# ; do \
+	# 	echo "Fetching GPG key $GPG_KEYS from $server"; \
+	# 	gpg --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$GPG_KEYS" && found=yes && break; \
+	# done; \
+	# test -z "$found" && echo >&2 "error: failed to fetch GPG key $GPG_KEYS" && exit 1; \
+	# gpg --batch --verify nginx.tar.gz.asc nginx.tar.gz \
+	# && rm -r "$GNUPGHOME" nginx.tar.gz.asc \
+
+	#&& mkdir -p /usr/src \
+	#&& tar -zxC /usr/src -f nginx-1.17.2.tar.gz \
+	#&& rm nginx-1.17.2.tar.gz \
 	&& cd /usr/src/nginx-$NGINX_VERSION \
 	&& ./configure $CONFIG --with-debug \
 	&& make -j$(getconf _NPROCESSORS_ONLN) \
@@ -134,6 +142,8 @@ RUN GPG_KEYS=B0F4253373F8F6F510D42178520A9993A1C052F8 \
 
 COPY nginx.conf /etc/nginx/nginx.conf
 COPY nginx.vh.default.conf /etc/nginx/conf.d/default.conf
+
+VOLUME [ "/etc/nginx" ]
 
 EXPOSE 80
 
